blog/urls.py
from django.contrib import admin
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('add/', views.add_blog, name='add_blog'),
    path('<int:blog_id>/', views.get_blog, name='get_blog'),
    path('<int:blog_id>/update_name/', views.set_blog_name, name='set_blog_name'),
    path('<int:blog_id>/delete/', views.delete_blog, name='delete_blog'),
    path('<int:blog_id>/name/', views.get_blog_name, name='get_blog_name'),
    path('react/', views.react_to_post, name='react_to_post'),
    path('<int:blog_id>/post/create/', views.add_post, name='add_post'),  
    path('<int:blog_id>/post/<int:post_id>/', views.get_post, name='get_post'), 
]


""" urlpatterns = [
    path('add/', views.add_blog, name='add_blog'),
    path('<int:blog_id>/', views.get_blog, name='get_blog'),
    path('<int:blog_id>/update_name/', views.set_blog_name, name='set_blog_name'),
    path('<int:blog_id>/delete/', views.delete_blog, name='delete_blog'),
    path('<int:blog_id>/name/', views.get_blog_name, name='get_blog_name'),
    path('react/', views.react_to_post, name='react_to_post'),
    path('<int:blog_id>/post/create/', views.add_post, name='add_post'),  
] """

blog_system/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from authorization import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('user/', include('users.urls', namespace='user')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import include, path

import blog
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render

from blog.models import Blog

# Create your views here.
def index(request):
    blogs = Blog.objects.all()
    context = {
        'blogs': blogs,
        'title': 'Main page',
    }
    return render(request, 'main/index.html', context)

templates/main/index.html
{% extends "based/base.html" %}

{% block content %}

    {% if blogs %}
        {% for blog in blogs %}
            <div class="alert alert-success mt-2">
                <h3>
                    {% if blog.id  %}
                        <a href={% url "blog:get_blog" blog.id %}>
                            {{ blog.title }}
                        </a>
                    {% else %}
                        <span>{{ blog.title }}</span>
                    {% endif %}
                </h3>
            </div>
        {% endfor %}
    {% else %}
        <h3>No blogs</h3>
    {% endif %}

{% endblock %}