blog/urls.py
from django.contrib import admin
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('add/', views.add_blog, name='add_blog'),
    path('<int:blog_id>/', views.get_blog, name='get_blog'),
    path('<int:blog_id>/update_name/', views.set_blog_name, name='set_blog_name'),
    path('<int:blog_id>/delete/', views.delete_blog, name='delete_blog'),
    path('<int:blog_id>/name/', views.get_blog_name, name='get_blog_name'),
    path('react/', views.react_to_post, name='react_to_post'),
    path('<int:blog_id>/post/create/', views.add_post, name='add_post'),  
    path('<int:blog_id>/post/<int:post_id>/', views.get_post, name='get_post'), 
]


""" urlpatterns = [
    path('add/', views.add_blog, name='add_blog'),
    path('<int:blog_id>/', views.get_blog, name='get_blog'),
    path('<int:blog_id>/update_name/', views.set_blog_name, name='set_blog_name'),
    path('<int:blog_id>/delete/', views.delete_blog, name='delete_blog'),
    path('<int:blog_id>/name/', views.get_blog_name, name='get_blog_name'),
    path('react/', views.react_to_post, name='react_to_post'),
    path('<int:blog_id>/post/create/', views.add_post, name='add_post'),  
] """

blog_system/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from authorization import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('user/', include('users.urls', namespace='user')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import include, path

import blog
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

users/urls.py
from django.contrib import admin
from django.urls import path

from users import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('registration/', views.registration_view, name='registration_view'),
    path('profile/', views.profile_view, name='profile_view'),
    path('logout/', views.logout_view, name='logout_view'),
]

templates/based/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
    <link rel="stylesheet" href="{% static "styles.css" %}">
</head>
<body>
  {% block navbar %}
      <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
          <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
          <span class="fs-4">system</span>
        </a>

        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
          <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'main:index' %}">Главная</a>
          {% if not user.is_authenticated %}
            <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'user:login_view' %}">Войти</a>
          {% else %}
            <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'user:profile_view' %}">Мой профиль</a>
          {% endif %}
          {% if user.is_superuser %}
            <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'admin:index' %}">Админ панель</a>
            <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'blog:add_blog' %}">Создать</a>
          {% endif %}
          {% if user.is_authenticated %}
          <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'user:logout_view' %}">Выйти</a>
          {% endif %}
    {% endblock navbar %}
        </nav>
      </nav>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>

</body>
</html>