blog/urls.py
from django.contrib import admin
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('add/', views.add_blog, name='add_blog'),
    path('<int:blog_id>/', views.get_blog, name='get_blog'),
    path('<int:blog_id>/update_name/', views.set_blog_name, name='set_blog_name'),
    path('<int:blog_id>/delete/', views.delete_blog, name='delete_blog'),
    path('<int:blog_id>/name/', views.get_blog_name, name='get_blog_name'),
    path('react/', views.react_to_post, name='react_to_post'),
    path('<int:blog_id>/post/create/', views.add_post, name='add_post'),  
    path('<int:blog_id>/post/<int:post_id>/', views.get_post, name='get_post'), 
]


""" urlpatterns = [
    path('add/', views.add_blog, name='add_blog'),
    path('<int:blog_id>/', views.get_blog, name='get_blog'),
    path('<int:blog_id>/update_name/', views.set_blog_name, name='set_blog_name'),
    path('<int:blog_id>/delete/', views.delete_blog, name='delete_blog'),
    path('<int:blog_id>/name/', views.get_blog_name, name='get_blog_name'),
    path('react/', views.react_to_post, name='react_to_post'),
    path('<int:blog_id>/post/create/', views.add_post, name='add_post'),  
] """

blog_system/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from authorization import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('user/', include('users.urls', namespace='user')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path

from users import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('registration/', views.registration_view, name='registration_view'),
    path('profile/', views.profile_view, name='profile_view'),
    path('logout/', views.logout_view, name='logout_view'),
]

users/models.py
from enum import unique
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, ForeignKey, TextField

from blog.models import Post

class User(AbstractUser):
    nickname = CharField(max_length=20, blank=True)
    roles = models.JSONField(default=list, blank=True)
    image = models.ImageField(blank=True, null=True, verbose_name='Аватар')

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

class TextComments(models.Model):
    text = TextField(null=True, blank=True)

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='users', null=True, blank=True)
    text = models.ForeignKey(TextComments, on_delete=models.CASCADE, related_name='text_comments', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey("blog.Post", on_delete=models.SET_NULL, related_name='comments', null=True, blank=True)

    class Meta:
        db_table = 'comment'
        verbose_name = 'Комментария'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return f"Comment by {self.user.username}: {self.text.text[:20]}"
    

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm

from users.models import TextComments, User

class UserLoginForm(AuthenticationForm):

    username = forms.CharField()
    password = forms.CharField()

    # username = forms.CharField(
    #     label = 'Имя',
    #     widget=forms.TextInput(attrs={"autofocus": True,
    #                                   'class': 'input-box',
    #                                   'placeholder': 'Enter your username'}))
    # password = forms.CharField(
    #     label = 'Пароль',
    #     widget=forms.PasswordInput(attrs={"autocomplete": "current-password",
    #                                       'class': 'input-box',
    #                                       'placeholder': 'Enter your password'})
    # )

    class Meta:
        model = User
        fields = ['username', 'password']

class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = [
            'username',
            'password1',
            'password2'
        ]

class ProfileForm(UserChangeForm):
    class Meta:
        model=User
        fields = [
            'image',
            'username',
        ]

        image = forms.ImageField()
        username = forms.CharField()    


class CommentForm(forms.ModelForm):
    text = forms.CharField()

    class Meta:
        model = TextComments
        fields = ['text']

users/views.py
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse

from users.forms import ProfileForm, UserLoginForm, UserRegistrationForm
from users.services.auth_service import AuthService

auth_service = AuthService()

def login_view(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth_service.login(request, username, password)
            if user:
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()

    context = {
        'title': 'Авторизация',
        'form': form
    }
    return render(request, 'users/login.html', context)

def registration_view(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = auth_service.register(
                username=form.cleaned_data['username'],
                password1=form.cleaned_data['password1'],
                password2=form.cleaned_data['password2']
            )
            auth_service.login(request, user.username, form.cleaned_data['password1'])
            return HttpResponseRedirect(reverse('user:profile_view'))
        else:
            print(form.errors)
    else:
        form = UserRegistrationForm()

    context = {
        'title': 'Регистрация',
        'form': form
    }
    return render(request, 'users/registration.html', context)

def profile_view(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            auth_service.update_user(
                user=request.user,
                image=form.cleaned_data.get('image'),
                username=form.cleaned_data.get('username')
            )
            return redirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)

    context = {
        'form': form
    }
    return render(request, 'users/profile.html', context)



def logout_view(request):
    auth.logout(request)
    return redirect(reverse('main:index'))

templates/users/login.html
{% extends "based/base.html" %}
{% load static %}

{% block content %}        
    <div class="login-container">
        <div class="login-box">
            <h2>Authorization</h2>
            <form action='{% url 'user:login_view'%}' method='post'>
                {% csrf_token %}
                {% if form.non_field_errors %}
                <p>{{form.non_field_errors}}</p>
                {% endif %}
                <div class="input-box">
                    <input type="text" placeholder='Enter your username' name="username" value={% if form.username.value %}{{ form.username.value }} {% else %} "" {% endif %} required>
                    <label></label>
                </div>
                <div class="input-box">
                    <input type="password" placeholder='Enter your password' name="password" required>
                    <label></label>
                </div>
                {% comment %} <div class="input-box">
                    <input type="text" name="username" required>
                    <label>Имя пользователя</label>
                </div>
                <div class="input-box">
                    <input type="password" name="password" required>
                    <label>Пароль</label>
                </div>{% endcomment %}
                <button type="submit">Войти</button>  
            </form>
            <br>
            <form action="{% url 'user:registration_view' %}" method='post'>
                {% csrf_token %}    
                <button type="submit">Создать аккаунт</button>
            </form> 
        </div>
    </div>
{% endblock content %}              

templates/users/profile.html
{% extends "based/base.html" %}
{% load static %}
{% block content %}
    <div class="login-container">
        <div class="login-box">
            <h2>Профиль пользователя</h2>
            <form action="{% url "user:profile_view" %}" method="post">
                {% csrf_token %}
                <div class="input-box">
                    <p>Username</p>
                    <input type="text" name="username" id="username" value="{{ user.username }}" readonly>
                </div>
                <div class="input-box">
                    <p>Email:</p>
                    <input type="email" name="email" id="email" value="{{ user.email }}" readonly>
                </div>
                <button type="button">Редактировать профиль</button>
            </form>
        </div>
    </div>
{% endblock content %}

templates/users/registration.html
{% extends "based/base.html" %}
{% load static %}

{% block content %}
    <div class="login-container">
        <div class="login-box">
            <h2>Регистрация</h2>
            <form action="{% url 'user:registration_view' %}" method='post'>
                {% csrf_token %}
                <div class="input-box">
                    <input type="text" name="username" placeholder='Enter your username' value={% if form.username.value %}{{ form.username.value }} {% else %} ""{% endif %} required>
                    {% if form.username.errors %}{{ form.username.errors }}{% endif %}
                </div>
                <div class="input-box">
                    <input placeholder="Enter your password" type="password" name="password1" required>
                    {% if form.password1.errors %}{{ form.password1.errors }}{% endif %}
                </div>
                <div class="input-box">
                    <input placeholder="Repeat your password" type="password" name="password2" required>
                    {% if form.password2.errors %}{{ form.password2.errors }}{% endif %}
                </div>
                <button type="submit">Зарегистрироваться</button>
            </form>
        </div>
    </div>
{% endblock content %}